io:
  input: ../nero_ws/runs/cuccumber_peeling
  output: ../nero_ws/runs/swm/cucumber_peeling_lerobot_v3
  repo_id: cucumber_peeling_lerobot_v3
  max_episodes: null
  no_videos: true
  push_to_hub: false

task: cucumber_peeling
fps: 100

timeline:
  mode: raw_lowdim_action_hold
  state_timestamp_path: teleop/timestamp_us
  action_anchor_timestamp_path: cameras/wrist/timestamp_us
  action_fps: 25
  max_action_gap_s: 0.020

features:
  observation.joint:
    rate: state
    dtype: float32
    shape: [7]
    h5_path: teleop/q_follower
    align: index
    lowpass: false
    # cutoff_hz: 15.0
    # order: 2
  observation.velocity:
    rate: state
    dtype: float32
    shape: [7]
    h5_path: teleop/dq_follower
    align: index
    lowpass: true
    cutoff_hz: 20.0
    order: 1
  observation.torque:
    rate: state
    dtype: float32
    shape: [7]
    h5_path: teleop/tau_follower
    align: index
    lowpass: true
    cutoff_hz: 20.0
    order: 1
  observation.delta_q:
    rate: state
    dtype: float32
    shape: [7]
    sources:
      - h5_path: teleop/q_cmd
        align: index
      - h5_path: teleop/q_follower
        align: index
    combine: subtract
    lowpass: false
    # cutoff_hz: 15.0
    # order: 2
  observation.tau_ext:
    rate: state
    dtype: float32
    shape: [7]
    h5_path: teleop/tau_ext_pred
    align: index
  observation.ee_pose:
    rate: state
    dtype: float32
    shape: [7]
    h5_path: teleop/ee_pose_follower
    align: index
    transform: ee_pose_matrix_to_quaternion
  action.joint:
    rate: action
    dtype: float32
    shape: [7]
    h5_path: teleop/q_follower
    timestamp_path: teleop/timestamp_us
    resample: next
  action.ee_pose:
    rate: action
    dtype: float32
    shape: [7]
    h5_path: teleop/ee_pose_follower
    timestamp_path: teleop/timestamp_us
    resample: next
    transform: ee_pose_matrix_to_quaternion
