# 推理用：
dataset:
  # root: data/xxx
  # repo_id: xxx
inferencer:
  inference_plot_save_path: 
  # ckpt_path: outputs/wrench_bg/v2/exp3/checkpoints/epoch_290_val_loss_0.0531.pt
  # ckpt_path: outputs/wrench_bg/v2/exp11/checkpoints/epoch_046_val_loss_0.0555.pt
  ckpt_path: outputs/wrench_bg/v2/exp1/checkpoints/epoch_237_val_loss_0.0021.pt