# 推理用：
dataloader:
  repo_id: local/h5_to_lerobot_v3
  root: data/train_episode/wipe_board/wipe_board_lerobotv3
  # repo_id: wrench_bg_lerobotv3
  # root: data/train_episode/wrench_background/wrench_bg_lerobotv3
  load_images: false
  video_backend: torchcodec
  normalize_mode: gaussian
  horizon: 1
  lowdim_keys:
    q: observation.joint                     #q
    v: observation.velocity                  #v
    ee_pose: action.ee_pose                  #u             
    wrench: observation.ft_window            #lambda
  # image_keys:
  #   wrist: observation.images.wrist
  #   side_1: observation.images.side_1
  #   side_2: observation.images.side_2
  normalize_lowdim_keys: 
    - q 
    - v
    - ee_pose 
    - wrench

inferencer:
  ckpt_path: outputs/wrench_bg/v2/exp10/checkpoints/epoch_170_val_loss_0.0463.pt