"dataloader": {
        "history_horizon": H,
        "future_horizon": F,
    },
    "model": {
        "q_dim": 7,
        "v_dim": 7,
        "a_dim": 7,
        "tau_dim": 7,
        "wrench_dim": 6,
    },
    "train": {
        "hidden_dim": 256,
        "nhead": 4,
        "num_layers": 2,
        "dropout": 1e-3,
    },


dataloader:
  repo_id: wrench_bg_lerobotv3_
  root: data/train_episode/wrench_background/wrench_bg_lerobotv3_
  load_images: false
  video_backend: torchcodec
  normalize_mode: limit
  horizon: 3
  lowdim_keys:
    q: observation.joint                     #q
    v: observation.velocity                  #v
    a: observation.acceleration
    ee_velocity: observation.ee_velocity
    ee_acceleration: observation.ee_acceleration
    ee_pose: action.ee_pose                  #u             
    wrench: observation.ft_window            #lambda
  # image_keys:
  #   wrist: observation.images.wrist
  #   side_1: observation.images.side_1
  #   side_2: observation.images.side_2
  normalize_lowdim_keys: 
    - q 
    - v
    - a
    - ee_pose 
    - ee_acceleration
    - ee_velocity
    - wrench

  history_horizon: 8
  future_horizon: 8
model:
  q_dim: 7
  v_dim: 7
  a_dim: 7
  tau_dim: 7
  wrench_dim: 6
train:
  hidden_dim: 256
  nhead: 4
  num_layers: 2
  dropout: 1e-3
  
  scheduler:
    name: reduce_on_plateau
    factor: 0.5
    patience: 20
    min_lr: 1e-10

  batch_size: 512
  device: cuda:0
  num_workers: 32
  val_ratio: 0.2
  split_mode: sample   # sample(单点) episode
  seed: 42
  lr: 1e-4
  weight_decay: 1e-4
  num_epochs: 1000
  output_dir: outputs/wrench_bg/v2/h3_2
  monitor_key: val_loss
  top_k: 5
  
