dataloader:
  repo_id: test
  root: data/dynamic_test__new_lerobotv3
  load_images: false
  video_backend: torchcodec
  normalize_mode: null
  horizon: 1
  lowdim_keys:
    q: observation.joint                     #q
    v: observation.velocity                  #v
    a: observation.acceleration
    tau: observation.torque
    tau_ext: observation.tau_ext
    # ee_velocity: observation.ee_velocity
    # ee_acceleration: observation.ee_acceleration
    # ee_pose: action.ee_pose                  #u             
    wrench: observation.ft            #lambda


lowpass_filter:
  enabled: true
  sample_rate_hz: 120
  order: 2
  zero_phase: true
  derive_v_from_q: false
  derive_a_from_v: false
  fields:
    q:
      enabled: false
      cutoff_hz: 10.0
    v:
      enabled: true
      cutoff_hz: 20
    a:
      enabled: false
      cutoff_hz: 5.0
    tau:
      enabled: true
      cutoff_hz: 8.0
    tau_ext:
      enabled: false
      cutoff_hz: 8.0
    wrench:
      enabled: false
      cutoff_hz: 8.0

model:
  input_dims:
    q: 7
    v: 7
    a: 7
    ee_pose: 7
    ee_acceleration: 6
    ee_velocity: 6
  static_inputs:
    - q
    - ee_pose
  dynamic_inputs:
    - q
    - ee_pose
    - v
    - a
    - ee_acceleration
    - ee_velocity
train:
  hidden_dim: 256
  activation: silu
  use_norm: True
  dropout: 1e-3
  static_num_res_blocks: 3
  dynamic_num_res_blocks: 5

  scheduler:
    name: reduce_on_plateau
    factor: 0.5
    patience: 20
    min_lr: 1e-10

  batch_size: 512
  device: cuda:0
  num_workers: 32
  val_ratio: 0.2
  split_mode: sample   # sample(单点) episode
  seed: 42
  lr: 1e-4
  weight_decay: 1e-4
  num_epochs: 1000
  output_dir: outputs/wrench_bg/v2/h3_2
  monitor_key: val_loss
  top_k: 5
  
