dataloader:
  repo_id: local/h5_to_lerobot_v3
  root: data/train_episode/wipe_board/wipe_board_lerobotv3
  load_images: false
  video_backend: torchcodec
  normalize_mode: gaussian
  horizon: 8
  lowdim_keys:
    q: observation.joint                     #q
    v: observation.velocity                  #v
    ee_pose: action.ee_pose                   #u
    torque: observation.torque               #u
    wrench: observation.ft_window            #lambda
  image_keys:
    wrist: observation.images.wrist
    side_1: observation.images.side_1
    side_2: observation.images.side_2
  normalize_lowdim_keys: 
    - q 
    - v
    - ee_pose 
    - torque 
    - wrench
train:
  batch_size: 64
  num_workers: 4
  lr: 0.001
  weight_decay: 0.0001
  num_epochs: 20
  log_interval: 20
  

